In [19]:
import numpy as np
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(np.zeros((3, 3)))
print(np.ones((2, 4)))
np.eye(3)
np.arange(0, 10, 2)
np.linspace(0, 1, 5)
np.random.rand(3, 2)
np.random.randn(3, 2)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[ 0.02921605,  1.88526415],
       [-0.44007121, -1.31383597],
       [-1.32029744,  1.15647044]])

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('Shape=',arr.shape)
print('Dimension=',arr.ndim)
print('Size=',arr.size)
print('Data Type=',arr.dtype)


Shape= (2, 3)
Dimension= 2
Size= 6
Data Type= int64


In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)
print(np.sin(a))


[5 7 9]
[ 4 10 18]
[0.84147098 0.90929743 0.14112001]


In [8]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
A @ B


array([[19, 22],
       [43, 50]])

In [16]:
arr = np.array([1,2,3,4])

print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.std())

10
2.5
4
1
1.118033988749895


In [17]:
arr = np.array([1,2,3,4,5])

print(arr[0])
print(arr[1:4])
print(arr[::2])

1
[2 3 4]
[1 3 5]


In [18]:
arr = np.arange(6)

print(arr)

new_arr = arr.reshape(2,3)

print(new_arr)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
